import type { Metadata } from "next";
import "./globals.css";

import { Roboto_Flex } from "next/font/google";

const robotoFlex = Roboto_Flex({
	subsets: ["latin"],
	weight: ["400", "700"],
	style: ["normal"],
	variable: "--font-roboto-flex",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${robotoFlex.variable}  antialiased bg-black`}>
				{children}
			</body>
		</html>
	);
}
